import { useCallback, useEffect, useLayoutEffect, useRef, useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { useNavigate } from "react-router-dom";
import "./CoverflowCarousel.css";

export const CoverflowCarousel = ({ slides }) => {
  const navigate = useNavigate(); const count = slides.length; const frameRef = useRef(null); const cardRefs = useRef([]); const posRef = useRef(0); const targetRef = useRef(0); const widthRef = useRef(0); const rafRef = useRef(null); const dragRef = useRef(null); const suppressClickRef = useRef(false); const [selected, setSelected] = useState(0);
  const indexAt = useCallback((pos) => ((Math.round(pos) % count) + count) % count, [count]);
  const paint = useCallback(() => { const width = widthRef.current; if (!width) return; const pitch = width * 1.07; cardRefs.current.forEach((card, index) => { if (!card) return; let offset = ((index - posRef.current) % count + count) % count; if (offset > count / 2) offset -= count; const distance = Math.abs(offset); const ramp = Math.pow(distance, .58); const tilt = Math.min(42 * ramp, 80) * Math.sign(offset); card.style.transform = `translateX(calc(-50% + ${offset * pitch}px)) translateZ(${-0.62 * width * ramp}px) rotateY(${-tilt}deg)`; card.style.opacity = String(Math.max(0, 1 - .11 * distance) * Math.min(1, Math.max(0, count / 2 - distance))); card.style.zIndex = String(100 - Math.round(distance)); }); }, [count]);
  const settle = useCallback((target) => { if (rafRef.current) cancelAnimationFrame(rafRef.current); targetRef.current = target; setSelected(indexAt(target)); const step = () => { const remaining = target - posRef.current; if (Math.abs(remaining) < .0004) { posRef.current = target; paint(); rafRef.current = null; return; } posRef.current += remaining * .16; paint(); rafRef.current = requestAnimationFrame(step); }; rafRef.current = requestAnimationFrame(step); }, [indexAt, paint]);
  const nudge = useCallback((by) => settle(Math.round(targetRef.current) + by), [settle]);
  useLayoutEffect(() => { const frame = frameRef.current; if (!frame) return; const measure = () => { if (cardRefs.current[0]) { widthRef.current = cardRefs.current[0].offsetWidth; paint(); } }; measure(); const observer = new ResizeObserver(measure); observer.observe(frame); return () => observer.disconnect(); }, [paint]);
  useEffect(() => () => rafRef.current && cancelAnimationFrame(rafRef.current), []);
  if (!count) return null; const active = slides[selected];
  return <div className="coverflow" role="region" aria-label="Artistas destacados" data-testid="artists-coverflow">
    <div ref={frameRef} className="coverflow-frame" tabIndex={0} onKeyDown={(e) => { if (e.key === "ArrowLeft") nudge(-1); if (e.key === "ArrowRight") nudge(1); }} onPointerDown={(e) => { if (rafRef.current) cancelAnimationFrame(rafRef.current); suppressClickRef.current = false; dragRef.current = { id: e.pointerId, x: e.clientX, pos: posRef.current }; }} onPointerMove={(e) => { const d = dragRef.current; if (!d || d.id !== e.pointerId) return; if (Math.abs(e.clientX - d.x) > 6 && !suppressClickRef.current) { suppressClickRef.current = true; e.currentTarget.setPointerCapture(e.pointerId); } posRef.current = d.pos - (e.clientX - d.x) / (widthRef.current * 1.07); setSelected(indexAt(posRef.current)); paint(); }} onPointerUp={(e) => { if (dragRef.current?.id === e.pointerId) { dragRef.current = null; settle(Math.round(posRef.current)); } }} data-testid="coverflow-drag-area">
      <div className="coverflow-stage">{slides.map((slide, index) => <button type="button" key={slide.id} ref={(node) => { cardRefs.current[index] = node; }} className="coverflow-card" aria-label={`Ver canciones de ${slide.artist}`} onClick={() => { if (suppressClickRef.current) { suppressClickRef.current = false; return; } navigate(`/catalogo?artist=${encodeURIComponent(slide.artist)}`); }} data-testid={`artist-slide-${slide.id}`}><img src={slide.imageUrl} alt={`Portada gráfica de ${slide.artist}`} draggable={false} /></button>)}</div>
    </div>
    <div className="coverflow-caption" key={active.id}><span data-testid="active-artist-number">{String(selected + 1).padStart(2, "0")} / {count}</span><div><h3 data-testid="active-artist-name">{active.artist}</h3><p data-testid="active-artist-song">{active.song}</p><small data-testid="active-artist-description">{active.description}</small></div><div className="coverflow-nav"><button onClick={() => nudge(-1)} aria-label="Artista anterior" data-testid="coverflow-previous-button"><ChevronLeft /></button><button onClick={() => nudge(1)} aria-label="Artista siguiente" data-testid="coverflow-next-button"><ChevronRight /></button></div></div>
  </div>;
};