import { useState } from "react";
import { CalendarDays, Check, Users } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/api/client";

export const ReservationSection = () => {
  const [form, setForm] = useState({ name: "", people: 2, date: "", time: "", contact: "", notes: "" }); const [sending, setSending] = useState(false); const [done, setDone] = useState(false);
  const update = (key) => (e) => setForm({ ...form, [key]: e.target.value });
  const submit = async (e) => { e.preventDefault(); setSending(true); try { await api.post("/reservations", { ...form, people: Number(form.people) }); setDone(true); toast.success("Solicitud de mesa enviada"); } catch (error) { toast.error(error.response?.data?.error || "No se pudo enviar la reserva"); } finally { setSending(false); } };
  return <section id="reservas" className="section reservation-section" data-testid="reservation-section"><div className="reservation-copy"><p className="eyebrow" data-testid="reservation-eyebrow"><span /> TU NOCHE EMPIEZA AQUÍ</p><h2 data-testid="reservation-heading">Reserva tu mesa.<br/><em>El escenario es tuyo.</em></h2><p data-testid="reservation-description">Cuéntanos cuándo vienes y prepararemos una experiencia a tu medida en el corazón de Madrid.</p><div className="reservation-facts"><span data-testid="reservation-capacity-info"><Users /> Grupos de 1 a 40</span><span data-testid="reservation-response-info"><CalendarDays /> Confirmación personal</span></div></div>
    <div className="reservation-panel">{done ? <div className="success-state" data-testid="reservation-success-message"><Check /><h3>Solicitud recibida</h3><p>Nos pondremos en contacto contigo para confirmar disponibilidad.</p><button className="text-button" onClick={() => { setDone(false); setForm({ name: "", people: 2, date: "", time: "", contact: "", notes: "" }); }} data-testid="new-reservation-button">Nueva reserva</button></div> : <form onSubmit={submit} data-testid="reservation-form"><label>Nombre<input required value={form.name} onChange={update("name")} placeholder="Nombre de la reserva" data-testid="reservation-name-input" /></label><div className="form-row"><label>Personas<input required type="number" min="1" max="40" value={form.people} onChange={update("people")} data-testid="reservation-people-input" /></label><label>Fecha<input required type="date" min={new Date().toISOString().split("T")[0]} value={form.date} onChange={update("date")} data-testid="reservation-date-input" /></label></div><div className="form-row"><label>Hora<input required type="time" value={form.time} onChange={update("time")} data-testid="reservation-time-input" /></label><label>Teléfono o email<input required value={form.contact} onChange={update("contact")} placeholder="Tu contacto" data-testid="reservation-contact-input" /></label></div><label>Notas <small>(opcional)</small><textarea value={form.notes} onChange={update("notes")} placeholder="Celebración, preferencias o cualquier detalle" data-testid="reservation-notes-input" /></label><button className="button button--primary button--wide" disabled={sending} data-testid="reservation-submit-button">{sending ? "Enviando…" : "Solicitar mesa"}</button></form>}</div>
  </section>;
};